// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'connection-failed-message'
  | 'connection-failed-title'
  | 'connection-success-message'
  | 'connection-success-title'
  | 'pref-api-token'
  | 'pref-auto-sync-enabled'
  | 'pref-auto-sync-interval'
  | 'pref-help'
  | 'pref-server-url'
  | 'pref-test-connection'
  | 'pref-title'
  | 'prefs-title'
  | 'reset-sync-label'
  | 'sync-button-label'
  | 'sync-button-tooltip'
  | 'sync-complete'
  | 'sync-failed';
