// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "serverUrl": string;
      "apiToken": string;
      "autoSyncInterval": number;
      "autoSyncEnabled": boolean;
      "groupLibraryId": number;
      "lastSyncTime": string;
      "itemKeyMap": string;
      "collectionKeyMap": string;
      "fileKeyMap": string;
      "deleteQueue": string;
    };
  }
}
